name: github pages

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          REACT_APP_BING_MAPS_KEY: ${{ secrets.REACT_APP_BING_MAPS_KEY }}
          REACT_APP_NASA_API_KEY: ${{ secrets.REACT_APP_NASA_API_KEY }}
          REACT_APP_NASA_MAP_KEY: ${{ secrets.REACT_APP_NASA_MAP_KEY }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build
